services:
  - type: web
    name: j-infinity
    runtime: node
    buildCommand: npm install --legacy-peer-deps; npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
